### ISSUE TITLE
Forestry exp drops dont stop screen flash

### ISSUE THREAD

**Issue by jevonsp** [jodelahithit/runelite-plugins#17]
It would be nice if participating in forestry events counted as still "woodcutting" as far as the plugin was concerned and not flash when actively doing them,

love the plugin, keep up the great work!

**Comment by erwinvc** [comment]
Hey, thanks for the suggestion!
I did some experimenting to find out what animations are used during the events and I've found the following:

**Rising Roots**: uses the normal woodcutting animation so this should already work.
**Struggling Sapling & Flowering Bush**: Both use the default bone burying animation which unfortunately isn't uniquely used for Forestry. I can't really use this since it would conflict with other animations and could potentially break the plugin in certain situations.
**Leprechaun**: No animations used.

Since my plugin is based completely on player animations, there's not much for me to work with and it would be pretty difficult for me to add support for these events. However, I've found that, since all events require a lot of walking, using the 'Disable overlay while walking' feature, optionally with a high delay of around 5 seconds should be sufficient.

Please let me know if I've missed something or if you see any other options!

**Comment by Brasolis** [comment]
Any chance you could add an option to put a delay whenever you get any xp at all? Then we could just set a custom delay for xp events which would cover all the awkard cases. Love the plugin overall though!

**Comment by erwinvc** [comment]
Great idea! I've added the proposed functionality so it should be available once the pull request has been accepted by the Runelite team.
